[package]
name = "igraph"
version = "0.1.0"
edition = "2021"

[lib]
name = "igraph"
path = "lib/igraph.rs"

[package.metadata.leptos]
output-name = "igraph-app"
site-root = "target/site"
site-addr = "127.0.0.1:3000"
reload-port = 3001
watch = true
env = "DEV"
bin-features = ["ssr"]
lib-features = ["hydrate"]
browserquery = "defaults"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
clap = { version = "4.5.0", features = ["derive", "env"] }
leptos = { version = "0.6.5", features = ["tracing", "ssr", "hydrate", "template_macro"] }
leptos_axum = { version = "0.6.5"}
leptos_meta = { version = "0.6.5"}
leptos_router = { version = "0.6.5"}
regex = { version = "1.10.3", features = ["use_std"] }
serde = { version = "1.0.196", features = ["derive", "alloc"] }
serde_json = { version = "1.0.113", features = ["alloc"] }
shlex = "1.3.0"
thiserror = "1.0.56"
tokio = { version = "1.36.0", features = ["fs", "full", "net", "time", "tracing"] }
tokio-util = { version = "0.7.10", features = ["tracing", "io", "codec", "net", "time"] }
trace = "0.1.7"
tracing = { version = "0.1.40", features = ["log", "async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["json", "matchers", "time", "tracing", "env-filter"] }
